version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: nebula
      POSTGRES_PASSWORD: nebula_pass
      POSTGRES_DB: nebula_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nebula-network

  mongo:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: nebula
      MONGO_INITDB_ROOT_PASSWORD: nebula_pass
      MONGO_INITDB_DATABASE: nebula
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - nebula-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: nebula
      ME_CONFIG_MONGODB_ADMINPASSWORD: nebula_pass
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    depends_on:
      - mongo
    networks:
      - nebula-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: nebula@gmail.com
      PGADMIN_DEFAULT_PASSWORD: nebula_pass
    ports:
      - "8082:80"
    depends_on:
      - postgres
    networks:
      - nebula-network

networks:
  nebula-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data: 